# splitbill-app/app/Dockerfile.golang
FROM golang:1.23-alpine AS builder

WORKDIR .
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN go build -o main .

FROM alpine:latest
# WORKDIR /app
# COPY --from=builder /app/main .
WORKDIR .
COPY --from=builder . .
EXPOSE 3000
CMD ["./main"]