# splitbill-app/app/Dockerfile.golang
FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY go.mod .
COPY go.sum .
COPY .env .
RUN go mod download

COPY . .
RUN go build -o main .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app .
EXPOSE 3000
CMD ["./main"]