// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/arifin2018/splitbill-arifin.git/controllers"
	"github.com/arifin2018/splitbill-arifin.git/controllers/SplitbillContollers"
	"github.com/arifin2018/splitbill-arifin.git/services/SplitbillServices"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeController() *controllers.AllControllers {
	splibillServiceImpl := splitbillservices.NewSplitbillServiceImpl()
	splitbillControllerImpl := splitbillcontollers.NewSplitbilController(splibillServiceImpl)
	allControllers := &controllers.AllControllers{
		SplitbilController: splitbillControllerImpl,
	}
	return allControllers
}

// wire.go:

var splitbilController = wire.NewSet(splitbillservices.NewSplitbillServiceImpl, wire.Bind(new(splitbillservices.SplibillService), new(*splitbillservices.SplibillServiceImpl)), splitbillcontollers.NewSplitbilController, wire.Bind(new(splitbillcontollers.SplitbilController), new(*splitbillcontollers.SplitbillControllerImpl)))

var setAllControllers = wire.NewSet(

	splitbilController, wire.Struct(new(controllers.AllControllers), "*"),
)
